// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import java.util.function.DoubleSupplier;

import frc.robot.subsystems.Drivetrain;
import frc.robot.RobotContainer;

/**
 *
 */
public class DefaultDrivetrain extends CommandBase {

        private final Drivetrain m_drivetrain;


    public DefaultDrivetrain(Drivetrain subsystem) {

        m_drivetrain = subsystem;
        addRequirements(m_drivetrain);

    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        
        m_drivetrain.arcadeDrive(
            0.75 * RobotContainer.getdriveStick().getLeftY(), //Up and down on drive stick
            0.75 * RobotContainer.getdriveStick().getLeftX() //Left and right on drive stick
        );

        /*
        m_drivetrain.tankDrive(
            RobotContainer.getdriveStick().getLeftY(), 
            RobotContainer.getdriveStick().getRightY()
        );
        */
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_drivetrain.stopMotors();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;
    }
}
